name: Docker Image
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 100
      - uses: docker/setup-buildx-action@v1
      - name: set tag
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          VERSION=$(echo "$TAG" | cut -d '+' -f 1)
          BUILD=$(echo "$TAG" | cut -d '+' -f 2)
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=build::$BUILD"
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/cownetwork/tuinity:${{ steps.tag.outputs.version }}-${{steps.tag.outputs.build}}
